import { describe, expect, it } from 'vitest';
import { unzipSync, strFromU8 } from 'fflate';
import { createFileSource, createPackageSource, exportWorldPackageAsync, loadWorld, validateWorld } from './index';

const sourceRoot = decodeURIComponent(new URL('../../../worlds/examples/echo-world', import.meta.url).pathname);
const archivePath = decodeURIComponent(new URL('../../../worlds/examples/echo-world.😭', import.meta.url).pathname);

describe('checked-in example package',()=>{it('stays in sync with its source directory',async()=>{const fromDirectory=await loadWorld(createFileSource(sourceRoot), { eagerAssets: true }); const fromArchive=await loadWorld(await createPackageSource(archivePath), { eagerAssets: true }); expect([...fromArchive.entities.keys()].sort()).toEqual([...fromDirectory.entities.keys()].sort()); expect(fromArchive.world.id).toBe(fromDirectory.world.id); expect(validateWorld(fromArchive).filter(issue=>issue.level==='error')).toEqual([]); expect(fromArchive.packageFiles.size).toBe(fromDirectory.packageFiles.size); expect([...fromArchive.packageFiles.keys()].sort()).toEqual([...fromDirectory.packageFiles.keys()].sort());});});

describe('example world fog coverage',()=>{it('gives every character a self rule and different knowledge levels',async()=>{const data=await loadWorld(await createPackageSource(archivePath)); for(const character of [...data.entities.values()].filter(entity=>entity.type==='character')){const self=data.links.get(character.id); expect(self,`${character.id} should expose graph links`).toBeDefined(); const rules=(character as {knowledge?:{target:string;access:string}[]}).knowledge ?? []; expect(rules.some(rule=>rule.target===character.id),`${character.id} should know itself`).toBe(true);} const aria=data.entities.get('character:aria') as {knowledge?:{target:string;access:string}[]}; const borin=data.entities.get('character:borin') as {knowledge?:{target:string;access:string}[]}; expect(aria.knowledge?.find(rule=>rule.target==='category:harbor')?.access).toBe('full'); expect(borin.knowledge?.find(rule=>rule.target==='category:harbor')?.access).toBe('partial');});});

describe('example package export determinism',()=>{it('re-exports the same entry list after a load',async()=>{const data=await loadWorld(await createPackageSource(archivePath)); const files=unzipSync(await exportWorldPackageAsync(data)); const original=unzipSync(new Uint8Array(await (await import('node:fs/promises')).readFile(archivePath))); expect(Object.keys(files).sort()).toEqual(Object.keys(original).sort()); expect(strFromU8(files['manifest.yaml'])).toContain('echo-world'); expect(strFromU8(files['index/entities.yaml'])).toContain('character:borin');});});
